node/handlers.c

Remove problematic use of fork from node controller.

Hypervisor fork() removal, fixes locking issue

---

node/handlers_default.c
storage/blobstore.c

Node controller libvirt connection fixes.
This pull request fixes Corymbia/eucalyptus#6 and EUCA-13446

Node controller libvirt connection fixes

---

clc/modules/msgs/src/main/java/com/eucalyptus/util/ChannelBufferStreamingInputStream.java
clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectFactoryImpl.java

S3 fix for upload concurrency and timeout handling.
This pull request fixes Corymbia/eucalyptus#11 and EUCA-13452

S3 increase max put threads and fail fast on timeouts

---

clc/modules/simpleworkflow/src/main/java/com/eucalyptus/simpleworkflow/tokens/TaskTokenManager.java
clc/modules/tokens/src/main/java/com/eucalyptus/tokens/SecurityTokenManagerImpl.java

Fix resource leak for simple workflow and token service.
This pull request fixes Corymbia/eucalyptus#9 and EUCA-13449

Simple workflow and token service token resource release

---

tools/config-no-polkit

- Correctly handles duplicate directives
- Closes #21

GH-21 tools/config-no-polkit has a runtime error

---

clc/modules/msgs/src/main/java/com/eucalyptus/entities/Entities.java
clc/modules/simpleworkflow/src/main/java/com/eucalyptus/simpleworkflow/SimpleWorkflowService.java

Simple workflow update to use pessimistic locking for better peformance with multiple ufs hosts.
This pull request fixes Corymbia/eucalyptus#8 and EUCA-13448

Simpleworkflow lock workflow execution for updates

---

clc/modules/msgs/src/main/java/com/eucalyptus/configurable/StaticDatabasePropertyEntry.java
clc/modules/msgs/src/main/java/com/eucalyptus/ws/StackConfiguration.java
clc/modules/msgs/src/main/java/com/eucalyptus/ws/WebServices.java

Update configuration for server pool size and async internal operations.
This pull request fixes Corymbia/eucalyptus#12

Configuration update for server threading and async internal operations

---

clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageAvailabilityEventListener.java

This pull request causes the calculation of s3 objects total size to be skipped when the s3 capacity has the default value. This allows the cloud administrator to enable/disable calculation as desired, to disable (i.e. reset to default):
```
objectstorage.max_total_reporting_capacity_gb = 2147483647
```
Note that this configuration is used for reporting only.
Fixes Corymbia/eucalyptus#50

S3 usage information now calculated only when capacity is configured

---

storage/storage-windows.c
util/euca_auth.c

Update to our use of openssl for compatibility with 1.1.0+.
https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Compatibility_Layer

Update OpenSSL api use for compatibility with 1.0.x and 1.1.x versions

---

node/handlers.c
node/handlers_kvm.c
util/data.h

Merge 4.4.5 changes to master branch.

Merge 4.4.5 to master

---

clc/modules/core/src/main/java/com/eucalyptus/upgrade/Upgrades.java

Modify detection of schema changes on start up to ignore hibernate configurations `EntityTuplizerFactory`.
The serialized output for `EntityTuplizerFactory` differs for different evaluations even when there are no changes to configuration. This can cause the recorded SHA-256 hash for each persistence context to vary leading to (slow) schema update handling incorrectly being triggered on `eucalyptus-cloud` service restart.

Schema upgrade skipping avoid incorrect configuration change detection

---

rpm/eucalyptus.spec

We now require the latest eucalyptus selinux and java dependencies packages.

Update rpm requires for eucalyptus java deps and selinux

---

clc/modules/core/src/main/java/com/eucalyptus/util/async/AsyncProxy.java
clc/modules/loadbalancing/ivy.xml
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancingHostedZone.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancingServiceBootstrapper.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/dns/LoadBalancerResolver.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/dns/LoadBalancerRoute53AliasResolver.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/service/LoadBalancingService.java

ELB service update to create a route53 hosted zone (when enabled) and expose via cloudformation resource attributes and describe load balancer responses.

ELB support for route53 load balancer alias target

---

clc/modules/core/src/main/java/com/eucalyptus/ws/server/JsonPipeline.java

Builds on Corymbia/eucalyptus#213 to support request decoding for JSON pipelines.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=526
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/54/
Test: /job/eucalyptus-5-qa-fast/82/
Demo is that existing tests pass, the functionality is the same as with query pipelines.

Message processing JSON pipeline request decoding

---

clc/modules/compute-backend/src/main/java/com/eucalyptus/vmtypes/VmTypes.java

On upgrade to 5.0 populate the new disk count property for instance types to the predefined default value.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=649
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/109/
Test: /job/eucalyptus-5-qa-fast/116/
The demo is to manually run the upgrade:
```
true
```

EC2 instance type upgrade for disk count

---

clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/providers/s3/S3ProviderClient.java

4.4 : S3 close http connection when testing backend provider

---

storage/storage-windows.c

4.4 : Node controller windows password encryption

---

clc/modules/cluster-manager/src/main/java/com/eucalyptus/compute/vpc/NatGatewayHelper.java
clc/modules/cluster-manager/src/main/java/com/eucalyptus/compute/vpc/VpcWorkflow.java

4.4 : EC2 VPC nat gateway private ip reservation remains pending / is removed

---

clc/modules/cluster-manager/src/main/java/com/eucalyptus/compute/metadata/VmMetadata.java
clc/modules/cluster-manager/src/main/java/com/eucalyptus/vm/VmInstanceMetadata.java
clc/modules/msgs/src/main/java/com/eucalyptus/auth/util/Identifiers.java

4.4 : EC2 instance metadata v2 api

---

clc/modules/block-storage/derby.log
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancers.java
clc/modules/object-storage/derby.log

4.4 : ELB Convert InstanceProtocol to upper case

---

clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java

4.4 : ELB ignore servo instance activity task failures for pending vms

---

clc/modules/core/src/main/java/com/eucalyptus/ws/server/Pipelines.java

The topology resolver allows use of region endpoints for services but the pipeline lookup only supported region names with spoofed endpoints.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=927
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/228/
Test: /job/eucalyptus-5-qa-fast/170/
Demo is that region endpoints can be used for most services:
```
#
system.dns.dnsdomain = qa18.eucalyptuscloud.net
#
#
region.region_name = cloud-1
#
#
REGIONS	http://ec2.qa18.eucalyptuscloud.net:8773/	cloud-1
#
```
which shows using the region `cloud-1` in the endpoint name for ec2.

Service regional endpoint support

---

clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/ComputeApi.java

Update for the internal compute api.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1062
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1064
Relates to: corymbia/eucalyptus#271

EC2 internal compute api update

---

clc/modules/core/src/main/java/com/eucalyptus/util/dns/DomainNameRecords.java
clc/modules/dns/src/main/java/com/eucalyptus/dns/resolvers/GenericDnsResolver.java

Merge to master for 6.0.
Relates to issue: corymbia/eucalyptus#273
Relates to pull request: corymbia/eucalyptus#274

DNS negative ttl configuration (master)

---

clc/modules/route53/src/main/java/com/eucalyptus/route53/service/dns/Route53DnsResolver.java

Merge to master for corymbia/eucalyptus#278
> When there is an AAAA query for which there is no record, but there is a corresponding A record, respond with no data rather than NXDOMAIN. Responding that the domain does not exist is incorrect and can cause name resolution issues.

Route53 respond with no data rather than nxdomain for AAAA (master)

---

clc/modules/route53/src/main/java/com/eucalyptus/route53/service/dns/Route53DnsResolver.java

When there is an `AAAA` query for which there is no record, but there is a corresponding `A` record, respond with no data rather than `NXDOMAIN`. Responding that the domain does not exist is incorrect and can cause name resolution issues.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1123
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1124
Demo is that we now respond with `NOERROR`:
```
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.4 <<>> AAAA console.cloud-ansdevdnd.qa.eucalyptuscloud.net @10.111.10.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21247
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; …
```

Route53 respond with no data rather than nxdomain for AAAA

---

clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/VolumeManager.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/VolumeUpdateEventListener.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/Volumes.java
clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/blockstorage/Volume.java
clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/blockstorage/VolumeModification.java
clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java

Support for asynchronous EC2 modify volume and support for describing volumes modifications.
Some errors that previously occurred on modify volume will now be reflected in the state/message for the resulting volumes modification item.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1055
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1056
Follow on for corymbia/eucalyptus#268
Part of issue corymbia/eucalyptus#267

EC2 DescribeVolumesModifications and async ModifyVolume

---

clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/ComputeApi.java
clc/modules/core/src/main/java/com/eucalyptus/util/MessageValidation.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/Loadbalancingv2MessageValidation.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/Action.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/Certificate.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateListenerType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateLoadBalancerType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateRuleType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateTargetGroupType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/DescribeLoadBalancerAttributesResult.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/FixedResponseActionConfig.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/HttpHeaderConditionConfig.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/LoadBalancerAttributes.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/Matcher.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/ModifyLoadBalancerAttributesResult.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/ModifyLoadBalancerAttributesType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/RedirectActionConfig.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/SecurityGroups.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/SubnetMapping.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/Subnets.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/TagDescription.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/TargetGroupStickinessConfig.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/TargetGroupTuple.java
clc/modules/loadbalancingv2-common/src/test/java/com/eucalyptus/loadbalancingv2/common/Loadbalancingv2MessageValidationSpecification.groovy
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Workflow.java

Update message validation and move compute api method to core from `LoadBalancingComputeApi` and remove it.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1241
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1242

ELBv2 message validation and compute api clean up

---

clc/modules/compute-backend/src/main/java/com/eucalyptus/address/AddressManager.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/address/Addresses.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/vpc/VpcManager.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/network/NetworkGroupManager.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/tags/TagHelper.java
clc/modules/compute-backend/src/main/java/com/eucalyptus/vm/VmControl.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/AllocateAddressType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateDhcpOptionsType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateInternetGatewayType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateLaunchTemplateType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateNatGatewayType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateNetworkAclType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateNetworkInterfaceType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateRouteTableType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateSecurityGroupType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateSubnetType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/CreateVpcType.java
clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/policy/ComputePolicySpec.java

EC2 tag on create or allocate for additional resource types.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1232
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1234
Demo is that tags can be added on create:
```
eipalloc-622a55b545410a5d2      vpc     10.111.10.169
ADDRESSES       eipalloc-622a55b545410a5d2      vpc     10.111.10.169
TAGS    TestTagName     TestTagValue
sg-227658fab8a4922eb
SECURITYGROUPS  test    sg-227658fab8a4922eb    test    000392544300    vpc-6ad7a7f6b67b4477b
IPPERMISSIONSEGRESS     -1
IPRANGES        0.0.0.0/0
TAGS    TestTagName     TestTagValue
LAUNCHTEMPLATE  2021-05-13T16:32:27.675000+00:00        arn:aws:iam::000392544300:root  1       1       lt-317fb967751c2de6c    test
LAUNCHTEMPLATES …
```

EC2 tag resources on create

---

clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/Loadbalancingv2Metadata.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/Loadbalancingv2ResourceName.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateListenerType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateRuleType.java
clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/CreateTargetGroupType.java
clc/modules/loadbalancingv2-common/src/main/resources/loadbalancingv2-binding.xml
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/Taggable.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/Tags.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Listener.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/ListenerRule.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/ListenerRuleTag.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/ListenerTag.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancerTag.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/PersistenceTags.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Tag.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroup.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroupTag.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/TagView.java

ELBv2 actions for tagging:
* AddTags
* DescribeTags
* RemoveTags
and support for tags on create of listeners, listener rules, load balancers and target groups.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1285
Deploy: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1286
Demo is that tags can be added, updated, described and removed:
```
LOADBALANCERS	2021-05-27T16:54:42.481Z	balancer-1-000186855777.lb.qa64.eucalyptuscloud.net	ipv4	arn:aws:elasticloadbalancing::000186855777:loadbalancer/app/balancer-1/0485d9404ae6780b	balancer-1	internet-facing	application	vpc-0fcbe31f2e33f64f9
AVAILABILITYZONES	subnet-fa7532064ae84d4a5
SECURITYGROUPS	sg-1a81bcb9e2533f3b6
STATE	provisioning
TAGDESCRIPTIONS …
```

ELBv2 tagging

---

clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancerHelper.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java
clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingWorkflows.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Workflow.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Listener.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Target.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroup.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/servo/Loadbalancingv2ServoMetadataSource.java
clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/servo/SwitchedServoMetadataSource.java

ELBv2 health checks for targets and describe target group by load balancer arn.
Initial draft requires an update once other pending elbv2 pull requests are merged.

ELBv2 target health

---

clc/modules/autoscaling-backend/src/main/java/com/eucalyptus/autoscaling/activities/ActivityManager.java

ELBv2 target health checks for AutoScaling.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1315
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1316
Tested by manually updating the health state of a target in the load balancer database to cause a health check failure and verifying the instance was replaced in the autoscaling group:
```
AUTO-SCALING-GROUP	elbv2-as-1-AutoScalingGroup-QTXDRFZ7BQITA	elbv2-as-1-LaunchConfiguration-3TRY9SGEYZVIW	cloud-1a	0	1	1	Default
INSTANCE	i-75e623770e485b769	cloud-1a	Pending	Healthy	elbv2-as-1-LaunchConfiguration-3TRY9SGEYZVIW
TAG	auto-scaling-group	elbv2-as-1-AutoScalingGroup-QTXDRFZ7BQITA	aws:cloudformation:logical-id	AutoScalingGroup	true
TAG	auto-scaling-group	elbv2-as-1-AutoScalingGroup-QTXDRFZ7BQITA …
```

AutoScaling ELBv2 target health monitoring

---

clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2LoadBalancerResourceAction.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2TargetGroupResourceAction.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/util/MessageHelper.java

CloudFormation tags for elbv2 resources:
* `AWS::ElasticLoadBalancingV2::LoadBalancer`
* `AWS::ElasticLoadBalancingV2::TargetGroup`
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1311
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1312
Tested create/update of tags defined in a template:
```
LoadBalancer:
Type: AWS::ElasticLoadBalancingV2::LoadBalancer
Properties:
Scheme: internet-facing
Type: application
SecurityGroups:
- !GetAtt SecurityGroupLoadBalancer.GroupId
Subnets:
- !Ref SubnetId
Tags:
- Key: a
Value: 1
...
```
and verified present on stack resources using elbv2 describe tags:
```
TAGDESCRIPTIONS	arn:aws:elasticloadbalancing::000879075798:loadbalancer/app/elbv2-3-LoadBalanc-EK3O0HWENXSQ6/6b83b3dc883f8da4
TAGS	a	1
TAGS …
```

CloudFormation elbv2 tags

---

clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2LoadBalancerResourceAction.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2TargetGroupResourceAction.java

CloudFormation ELBv2 resource update for load balancer and target group attribute support.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1341
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1342
Tested using a CloudFormation template that set attributes and with changes from corymbia/eucalyptus#303 merged:
```
#
arn:aws:cloudformation::000225583653:stack/elbv2-1/5f45d8a9-2ce9-40a5-bc94-0137b1b167d5
#
#
LOADBALANCERS	ZAAGJNMOKPSCKA	2021-06-09T18:46:20.822Z	elbv2-1-LoadBalanc-RCLDPKWZPYH60-000225583653.lb.qa64.eucalyptuscloud.net	ipv4	arn:aws:elasticloadbalancing::000225583653:loadbalancer/app/elbv2-1-LoadBalanc-RCLDPKWZPYH60/602d27913f3f4864	elbv2-1-LoadBalanc-RCLDPKWZPYH60	internet-facing	application	vpc-e79187aae8f042a24
AVAILABILITYZONES …
```

CloudFormation ELBv2 load balancer and target group attributes

---

clc/modules/core/src/main/java/com/eucalyptus/ws/server/Pipelines.java

Chunk aggregation handler for internal soap request pipeline.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1370
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1371
Fixes corymbia/eucalyptus#307

Chunk aggregation for internal requests

---

clc/modules/core/src/main/java/com/eucalyptus/ws/server/Pipelines.java

Merge to master for 5.2 issue corymbia/eucalyptus#307
> Chunk aggregation handler for internal soap request pipeline.

Chunk aggregation for internal requests (master)

---

clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSRDSDBInstanceResourceAction.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSRDSDBSubnetGroupResourceAction.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSRDSDBInstanceResourceInfo.java
clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSRDSDBSubnetGroupResourceInfo.java
clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/RdsMetadata.java
clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/policy/RdsResourceName.java
clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/policy/RdsResourceNameException.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/RdsService.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/DBInstances.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/DBSubnetGroups.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/Taggable.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/Tags.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/DBInstance.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/DBInstanceRuntime.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/DBInstanceTag.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/DBSubnetGroup.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/DBSubnetGroupTag.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/PersistenceTags.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/Tag.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/views/DBInstanceView.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/views/DBSubnetGroupView.java
clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/views/TagView.java

RDS tagging actions and tag on create for db instances and db subnet groups. 
CloudFormation support for tags on rds resources.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1400 
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1401
Relates to corymbia/eucalyptus#257

RDS tagging

---

clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/DescribeVpcClassicLinkResponseType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/DescribeVpcClassicLinkType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcClassicLinkSetType.java
clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcClassicLinkType.java
clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-14-10-01.xml
clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-15-10-01.xml
clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vpc/Vpcs.java
clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java

Merge to master for the 5.2 ec2 vpc classic link binding fix corymbia/eucalyptus#322
> Fix the query request binding for the ec2 vpc DescribeVpcClassicLink action and add a hard-coded false response for the classic link status of all vpcs.
Relates to corymbia/eucalyptus#321

EC2 VPC DescribeVpcClassicLink binding and response (master)
