Corymbia/eucalyptus

- clc/modules/msgs/src/test/java/com/eucalyptus/auth/principal/PrincipalTest.groovy
Fix unit test that can fail depending on test execution order.
> Ensure ern builder is configured for principal unit test

- tools/libvirt.xsl
This pull request adds smbios information for ec2 instances. Recent versions of cloud-init use this to detect running in ec2 prior to attempting instance meta-data access on boot.
This pull request fixes Corymbia/eucalyptus#2 and EUCA-13331
> EC2 libvirt smbios info for ec2 identification

- storage/blobstore.c
- storage/vbr.c
Node controller blobstore timeouts addressed by allowing for high load and ensuring retries occur when needed.
This pull request fixes Corymbia/eucalyptus#13
> Increase blobstore find/delete timeouts

- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/handlers/ObjectStorageGETOutboundHandler.java
S3 GET responses now have a close header when the connection is being closed.
This pull request fixes Corymbia/eucalyptus#17
> S3 add connection close header for object gets

- clc/modules/msgs/src/main/java/com/eucalyptus/bootstrap/BootstrapArgs.java
Remove the reachable host attempt from bootstrap unless enabled by system property.
This pull request fixes Corymbia/eucalyptus#26
> Remove bootstrap reachable host attempt

- clc/modules/autoscaling-backend/src/main/java/com/eucalyptus/autoscaling/activities/ActivityManager.java
Auto scaling distinct backoff for launch vs metrics activities so metrics gathering does not clear the failure counter for launch attempts.
This pull request fixes Corymbia/eucalyptus#23
> Auto scaling distinct backoff for launch/terminate activities

- clc/modules/msgs/src/main/java/com/eucalyptus/component/ComponentId.java
- clc/modules/msgs/src/main/java/com/eucalyptus/ws/server/ServiceAccessLoggingHandler.java
- clc/modules/simpleworkflow-common/src/main/java/com/eucalyptus/simpleworkflow/stateful/PolledNotifications.java
Disable request logging for the internal polled notification service.
This pull request fixes Corymbia/eucalyptus#15
> Polled notifications service excluded from access logging

- clc/modules/msgs/src/main/java/com/eucalyptus/ws/server/ServiceContextHandler.java
These channel locals were not being cleaned up and causing memory to "leak". We could fix this by making them static, etc, but the functionality was broken since channelOpened was never called (handler added to pipeline after open?) so removing seems like a better option.
> Service context handler channel locals removed

- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/ceph/CanonicalRbdObject.java
- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdConnectionManager.java
- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdInputStream.java
- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdOutputStream.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/S3SnapshotTransfer.java
Ensure snapshot input stream closed on error. Shutdown rados on disconnect/close rather than waiting for finalization to do so and ensure rados init/shutdown is thread safe.
This pull request fixes Corymbia/eucalyptus#19 and EUCA-13199
> Ceph / snapshot transfer resource handling

- tools/libvirt.xsl
EC2 add explicit libvirt append attribute due to change in the default value for rhel 7.4 libvirt.
This pull request fixes Corymbia/eucalyptus#7 and EUCA-13447
> EC2 explicit libvirt append attribute due to rhel 7.4 default 

- clc/modules/msgs/src/main/java/com/eucalyptus/util/Subnets.java
Fixes recursive dns for cloud in a box deployments.
This pull request fixes Corymbia/eucalyptus#16
> EC2 fix subnet netmask to cidr prefix calculation for dns subnet check

- clc/modules/msgs/src/main/java/com/eucalyptus/ws/DelegatingChannel.java
- clc/modules/msgs/src/main/java/com/eucalyptus/ws/DelegatingChannelHandlerContext.java
- clc/modules/msgs/src/main/java/com/eucalyptus/ws/Handlers.java
S3 blocking back end activities moved off of the netty io thread.
This pull request fixes Corymbia/eucalyptus#18
> S3 chunked writes must not block io threads on flush

- node/xml.c
- storage/blobstore.c
- util/log.c
Node controller now uses a standard 0022 umask.
This pull request fixes Corymbia/eucalyptus#20
> Set umask consistently for thread safety

- rpm/eucalyptus.spec
This pull request updates the node controllers libvirt dependency to 2.0.0 or higher ensuring that functionality we now use (as of 4.4.3) is available.
> If the interface type presented to the host is "file", then the source element may contain an optional attribute append that specifies whether or not the information in the file should be preserved on domain restart. Allowed values are "on" and "off" (default). Since 1.3.1. 
https://libvirt.org/formatdomain.html#elementsConsole
rpm with this pull request:
```
libvirt >= 2.0.0
libvirt-python
libvirt.so.0()(64bit)
libvirt.so.0(LIBVIRT_0.0.3)(64bit)
libvirt.so.0(LIBVIRT_0.1.0)(64bit)
libvirt.so.0(LIBVIRT_0.1.9)(64bit)
libvirt.so.0(LIBVIRT_0.2.1)(64bit)
libvirt.so.0(LIBVIRT_0.3.2)(64bit)
libvirt.so.0(LIBVIRT_0.7.3)(64bit)
#
# …
```
> Update libvirt requirement to 2.0.0+

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/entities/ObjectEntity.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/asynctask/BucketReaperTask.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/metadata/DbObjectMetadataManagerImpl.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/metadata/ObjectMetadataManager.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/metadata/ObjectStateTransitions.java
This pull request adds a new flag to s3 object entities to indicate when version clean up may be needed. When an object version is set as the latest (i.e. version added or removed) we now also set the "cleanup required" flag. The clean up flag is only meaningful on the latest version of an object.
The bucket reaper task now performs version clean up only for these flagged objects rather than all objects in a bucket. This task clears the clean up flag after processing an object, allowing progress to be made even when there are many objects to be checked.
It is generally the case that periodic clean up is not required, as clean up is performed when updates to an object are made. Having a flag allows for manual triggering of object version clean up (via database change) should it ever be …
> S3 objects are now flagged when they may require cleanup

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/exceptions/s3/S3Exceptions.groovy
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
This pull request updates the error message (error code is not changed) when access is denied on s3 resource creation. Determining if a denial is actually due to a quota being exceeded would be convoluted, so for now there is a hint that the error could be caused by a quota.
> Object storage access denied on create error message updated

- node/handlers_default.c
Node controller now checks paths before attempting to move the console log to avoid spurious error log messages.
> Node controller error logging when console.log not present

- node/handlers_kvm.c
The node controller now sets an instance to "booting" state as soon as possible in order to avoid instance termination due to a race between the monitoring and reboot threads.
> EUCA-13018 - Set instance to BOOTING state ASAP to avoid
> race condition between monitoring and rebooting threads
> Node controller set instance to BOOTING state ASAP to avoid termination on race

- clc/modules/msgs/src/main/java/com/eucalyptus/crypto/CertificateProvider.java
- clc/modules/msgs/src/main/java/com/eucalyptus/crypto/Certs.java
- clc/modules/msgs/src/main/java/com/eucalyptus/crypto/DefaultCryptoProvider.java
This pull request simplifies generating an https certificate for web services that contains the correct metadata for the endpoints/buckets in use. If such a certificate is configured for trust then https can be used without also needing special configuration for the mismatched host name.
This support for the subject alternative names extension is not used by default, no change is expected in the default behaviour due to this pull request.
> Allow generation of correctly named https certificate

- node/handlers.c
- node/handlers_default.c
This pull request alters the node controllers monitoring thread behaviour so that an instance reported by libvirt as shutdown (etc) is ignored during an instances shutdown grace period. It is expected that during this time the terminating thread is active in `shutdown_then_destroy_domain` and will handle clean up for the instance.
If the monitoring thread processes the shutdown instance then artifacts can be left behind as libvirt is performing clean up while in this state.
With the fix in place the new INFO log message is seen during instance churn testing, but not the `failed to remove some artifacts` message:
```
2018-07-03 19:24:33  INFO | [i-58c5024b] ignoring hypervisor reported state Shutdown for terminating domain during grace period (60)
```
with context:
```
2018-07-03 19:24:31 …
```
> Node controller should allow grace period for termination

- clc/modules/core/build.gradle
In master netty was upgraded to the last 3.6.x maintenance release. This 3.6.10 release causes an issue with our dns udp listener where dns becomes unresponsive. Moving back a release to 3.6.9 resolves the issue.
> Netty 3.6.9 from 3.6.10 due to dns udp listener issue

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/entities/ObjectEntity.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/ObjectStorage.groovy
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/util/ObjectStorageProperties.java
- clc/modules/object-storage-common/src/main/resources/osg-binding.xml
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/binding/ObjectStorageGETBinding.java
Backport S3 v2 listing support for 4. This allows listing of objects in buckets with more than the page size (default 1000) with tools that use the v2 action such as the awscli:
```
2500
```
We retain support for the v1 listing.
Fixes Corymbia/eucalyptus#116
> S3 object listing v2 (4.4 backport)

- tools/libvirt.xsl
Update libvirt.xsl to set the recommended rng device.
> the recommended source of entropy is /dev/urandom
https://libvirt.org/formatdomain.html#elementsRng
Fixes Corymbia/eucalyptus#127
> EC2 libvirt generation should set recommended rng device

- cluster/handlers-state.c
- cluster/handlers.c
- cluster/server-marshal.c
- net/ebt_handler.c
- net/euca_gni.c
- net/ips_handler.c
- net/ipt_handler.c
- storage/vbr.c
- util/log.c
Some calls are missing a format string. I do not think any of these are vulnerabilities but it is a simple fix.
https://en.wikipedia.org/wiki/Uncontrolled_format_string
https://www.owasp.org/index.php/Format_string_attack
> Format string clean up

- rpm/eucalyptus.spec
The `python-argparse` package is not needed with python 2.7+ and is provided by the python package in rhel/centos 7.x, dependencies on this package are removed.
The `kvm` package is provided by `qemu-system-x86`, so dependencies are updated accordingly.
```
#
python-2.7.5-69.el7_5.x86_64
#
#
qemu-system-x86-2.0.0-1.el7.6.x86_64
#
#
```
> Update kvm and python-argparse package dependencies

- clc/modules/postgresql/conf/scripts/setup_db.groovy
- configure.ac
CentOS/RHEL 7 include ant 1.9.2 and postgres 9.2 which satisfy version requirements. 
The way these version checks are implemented prevents use of more recent compatible versions. Since there are no incompatible versions available from a supported os, the checks are removed rather than fixed.
> Remove incorrect and unnecessary ant and postgresql version checks

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMInstanceProfileResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSIAMInstanceProfileProperties.java
CloudFormation IAM instance profile resource now uses default of `/` for `Path` property.
Fixes corymbia/eucalyptus#104
> CloudFormation IAM instance profile resource path not required

- clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/vpc/VpcManager.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/CreateDefaultSubnetResponseType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/CreateDefaultSubnetType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/CreateDefaultVpcResponseType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/CreateDefaultVpcType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
- clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java
For `CreateDefaultSubnet` and `CreateDefaultVpc` actions, remove user facing service stub and add backend service messages and implementation.
Fixes corymbia/eucalyptus#119
> EC2 VPC implement CreateDefaultSubnet and CreateDefaultVpc actions

- node/handlers.c
- node/handlers_kvm.c
- util/data.h
This pull request addresses issues with the current fix for corymbia/eucalyptus#117 and also ensures that we do not attempt concurrent reboots for an instance. The previous fix assumes instances are not in the `RUNNING` state during reboot, but this is not correct as `RUNNING` is the expected state while the instance is shutting down. There is only a short period in the `SHUTDOWN` state when the vm has exited and clean-up is being performed.
We now track a `rebootTime` for instances which is the time the instance was last transitioned to the `BOOTING` state. This allows the maintenance thread to determine if a reboot is in progress; previously this was not easily distinguished from the initial boot.
The default values for `NC_BOOTING_CLEANUP_THRESHOLD` and `NC_REBOOT_GRACE_PERIOD_SEC` are …
> EC2 node controller instance reboot handling

- node/handlers_kvm.c
Decrement outgoing migration count outside of debug statement for correct value when using `INFO` level logging or higher.
Fixes corymbia/eucalyptus#142
> EC2 node migration decrement outbound counter when not logging at debug

- clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/metadata/VmMetadata.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vm/VmInstances.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vm/VmInstance.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vm/VmInstances.java
EC2 instance meta-data should be available while the instance is in the shutting-down or stopping states. One example use is performing some clean-up using aws apis on instance termination using credentials from an instance profile.
Fixes Corymbia/eucalyptus#158
> EC2 allow instance meta-data access during stop/shutdown

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/template/TemplateParser.java
CloudFormation yaml templates allow a short form for attribute access:
```
!GetAtt logicalNameOfResource.attributeName
```
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
This was causing an NPE for some usages which were not updated when yaml support was added.
> CloudFormation yaml template attribute short-hand

- clc/modules/compute-backend/src/main/java/com/eucalyptus/network/config/NetworkConfigurationApi.java
- clc/modules/core/src/main/java/com/eucalyptus/util/Yaml.java
- clc/modules/euare/src/main/java/com/eucalyptus/auth/euare/identity/region/RegionConfigurations.java
We now support YAML format for network and region cloud configuration properties but incorrectly reject the YAML start of document marker and a leading comment. One of the benefits of using YAML is that comments can be used so we should allow this.
> Cloud network/region configuration should allow start of document and comments for YAML

- clc/modules/postgresql/conf/scripts/setup_db.groovy
Postgresql now defaults to listening on localhost and the cluster address. To revert to the old behaviour add the following to `CLOUD_OPTS` in `eucalyptus.conf`:
```
-Deuca.db.host=0.0.0.0
```
> Postgresql host now configurable with defaults of cluster address

- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/providers/s3/S3ProviderClient.java
S3 provider connection test should close the http connection to ensure data from a previous response is not read on later requests. This was causing a `-1` status code to be incorrectly reported for some S3 implementations.
> S3 close http connection when testing backend provider

- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/ObjectStorageRESTPipeline.java
- clc/modules/walrus/src/main/java/com/eucalyptus/walrus/pipeline/WalrusRESTPipeline.java
Log a debug message rather than an error and stack trace for an invalid host header during service resolution.
> Object storage do not log error/stack trace for invalid http host header

- tools/generate-migration-keys.sh
Node controller migration key generation script should default `EUCA_USER` to `eucalyptus` rather than `root`.
> Node controller migration key EUCA_USER default

- net/dev_handler.c
- net/dev_handler.h
- rpm/eucalyptus.spec
Remove unused vlan utility functions and the corresponding `vconfig` (epel) rpm dependency.
Network modes using vlans were removed in 4.4 but these utility functions remained.
> Node controller remove vlan utility functions and vconfig dependency

- node/handlers.c
- util/eucalyptus.h
We added an `NC_ADDR` option for the node controller bind address in Corymbia/eucalyptus#161 . This change ensures that when an IP is configured (so not the `0.0.0.0` default) it is used as the node controllers IP in place of the current approach of detecting the IP to use via the hostname. 
In the default case behaviour is unchanged, the `NC_ADDR` will be absent or `0.0.0.0` and the node controllers IP will be detected.
> Node controller use configured NC_ADDR for node IP

- clc/modules/core/src/main/java/com/eucalyptus/auth/policy/PolicySpec.java
- clc/modules/core/src/test/java/com/eucalyptus/auth/policy/PolicyParserTest.java
Update iam policy syntax checking to allow hyphen `-` in the service name prefix for actions.
Fixes Corymbia/eucalyptus#170
> IAM policy parser should allow hyphen in service name

- clc/modules/core/src/main/java/com/eucalyptus/component/auth/SystemCredentials.java
- clc/modules/core/src/main/java/com/eucalyptus/crypto/KeyStore.java
- clc/modules/core/src/main/java/com/eucalyptus/crypto/util/AbstractKeyStore.java
- clc/modules/core/src/main/java/com/eucalyptus/crypto/util/PEMFiles.java
- clc/modules/core/src/test/java/com/eucalyptus/crypto/util/PEMFilesTest.java
Update utility methods to support certificate chains in addition to single certificates. This is useful when using a production https configuration where intermediate certificates may be required.
> Key store / PEM utility method updates for certificate chains

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/ResourceInfoHelper.java
CloudFormation `AWS::CloudFormation::Stack` outputs were not found when used as attributes from the parent stack. You can now use these attributes as expected, e.g.:
```
!GetAtt StackResourceName.Outputs.NestedStackOutputName
!GetAtt [StackResourceName, Outputs.NestedStackOutputName]
```
> CloudFormation fix attribute check for stack resources

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/CloudFormationService.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/config/CloudFormationProperties.java
- clc/modules/core/src/main/java/com/eucalyptus/configurable/PropertyChangeListeners.java
CloudFormation add properties for configuration of cloud-wide pseudo parameters `AWS::Partition` and `AWS::URLSuffix`.
```
#
cloudformation.pseudo_param_partition = aws
#
cloudformation.pseudo_param_urlsuffix = my-cloud-10-10-10-10.euca.me:8773
#
```
This allows deployments to mimic a particular aws partition if desired or to (or example) include a port number in the url suffix.
> CloudFormation allow configured partition and urlsuffix pseudo params

- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java
ELB servo vm instance activity task failures are now only tracked when the instance is not in the pending state.
Fixes corymbia/eucalyptus#180
> ELB ignore servo instance activity task failures for pending vms

- node/handlers.c
The node controller was checking the wrong length when outputting trace logging for not-ready services causing a crash.
> Node controller check not-ready services length for trace output

- net/eucanetd.c
- net/eucanetd.h
- net/eucanetd_edge.c
- systemd/units/eucanetd.service
eucanetd now supports running under systemd as a `simple` service, with an option to skip closing file descriptors, switching user and forking.
The call to `arping` is modified to suppress output as this otherwise now ends up in the journal. The clean up for ip addresses now calls `ip addr del` as we do in other areas to avoid failures on error code 2 which is expected if the address is not present (so the delete is now idempotent)
The unit file now includes:
```
PrivateTmp=true
ProtectHome=true
ProtectSystem=true
```
which provide some additional protections.
> eucanetd systemd mode

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/config/CloudFormationProperties.java
Input validation for the cloudformation urlsuffix pseudo parameter is overly restrictive, we should allow shorter dns labels.
> CloudFormation update validation for configured urlsuffix pseudo param

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/CloudFormationService.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/template/TemplateParser.java
CloudFormation update to allow use of `Export` for better portability of templates between aws and eucalyptus. 
Exports are now ignored rather than causing a failure.
> CloudFormation allow but ignore template exports

- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancerListener.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancers.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java
Update ELB listener protocol handling by adding a utility method for case-insensitively creating protocols from names.
Fixes Corymbia/eucalyptus#194
> ELB consistently allow for case-insensitive protocol names when creating listeners

- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancers.java
When the ELB listeners are empty there exists a case when the AWS SDK will add listeners using lower case values of the Protocol, i.e. "tcp" when the construct is expected the upper case value, i.e. "TCP". This adds the `toUpperCase()` function to convert the string when building the listener.
> Convert InstanceProtocol to upper case

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSEC2NatGatewayResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSEC2NetworkInterfaceAttachmentResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSEC2NetworkInterfaceResourceAction.java
Add missing `@ConfigurableClass` annotations for cloudformation resources so that configurable properties are discovered.
> CloudFormation timeouts not configurable for nat gateway and eni

- clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/metadata/VmMetadata.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vm/VmInstanceMetadata.java
- clc/modules/core/src/main/java/com/eucalyptus/auth/util/Identifiers.java
Insecurely implement enough of IMDSv2 to allow instances to access metadata when using recent versions of cloud-init (20.2+) that disable IMDSv1.
Fixes Corymbia/eucalyptus#196
> EC2 instance metadata v2 api (insecure)

- clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/vpc/NatGatewayHelper.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/compute/vpc/VpcWorkflow.java
When a NAT gateway is created a private ip address is allocated. This pull request ensures that the private ip resource reservation is extant and uses the existing helper method for the network interface resource release on delete.
Fixes corymbia/eucalyptus#198
> EC2 VPC nat gateway private ip reservation remains pending / is removed

- storage/storage-windows.c
Node controller windows instance password encryption fix.
Build: /job/eucalyptus-internal-5-build-random-rpms/221/
Stage: /job/eucalyptus-internal-5-stage-random/183/
Deploy: /job/eucalyptus-5-ansible-deploy/145/
Test: /job/eucalyptus-5-qa-fast/43/
Demo is that you can run a "windows" instance without the node controller crashing:
```
eucalyptus-5.0.0-0.221.wpe.as.el7.x86_64
...
...
...
...
...
...
...
```
After launch manually verify that instance goes to running and node controller does not crash. Note that the snapshot is registered with the `windows` platform. This is not a valid instance, but the test covers launch, which is where the issue occurs.
Fixes corymbia/eucalyptus#200
> EC2 node controller windows password encryption

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSRoute53RecordSetGroupResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSRoute53RecordSetResourceAction.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/Route53Service.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/dns/Route53DnsResolver.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/persist/entities/ResourceRecordSet.java
Route53 update to support `TXT` records and other changes needed for `certbot` such as the implementation of the `GetChange` action which will always return `INSYNC` as there is no delay applying changes in the current implementation.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=414
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/10/
Test: /job/eucalyptus-5-qa-fast/49/
Demo is that you can create and query `TXT` records:
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
HostedZone:
Type: AWS::Route53::HostedZone
Properties:
Name: example.com
TXTRecordSet:
Type: AWS::Route53::RecordSet
DependsOn: HostedZone
Properties:
HostedZoneName: example.com
Name: "txt.example.com"
ResourceRecords:
- '"textvaluehere"'
TTL: 300
Type: TXT …
```
> Route53 support for TXT records

- clc/modules/dns/src/main/java/com/eucalyptus/cloud/ws/DNSControl.java
Add a DNS option for configuration of the listen port:
```
```
The cluster interface will always have a listener on port `53` for internal use by instances.
Changing the listen port allows each host with a dns service to also run a public facing reverse proxy dns server such as `dnsdist` which would access the cloud public dns on the configured port.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=410
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/9/
Test: /job/eucalyptus-5-qa-fast/48/
Demo is that the listen port can be configured:
```
tcp        0      0 192.168.111.14:53       0.0.0.0:*               LISTEN      29398/java          
tcp        0      0 10.116.111.14:53        0.0.0.0:*               LISTEN      29398/java          
tcp        0      0 …
```
> DNS configurable listener port

- clc/modules/core/src/main/java/com/eucalyptus/util/dns/DomainNames.java
The suffix generated for nameserver names is incorrect, resulting in invalid names being present in dns responses. This pull request corrects the suffix so it is a number (1, 2, 3, etc)
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=450
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/22/
Test: /job/eucalyptus-5-qa-fast/59/
Demo is that the nameserver names are now correct:
```
eucalyptus-5.0.0-0.92.dnsnsname.el7.x86_64
ns1.nc04-euca.appscale.net.
```
> DNS nameserver suffix

- clc/modules/core/src/main/java/com/eucalyptus/util/async/AsyncRequestHandler.java
To make issues easier to debug we should correctly track whether a message has been sent successfully.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=457
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/24/
Test: /job/eucalyptus-5-qa-fast/61/
The demo is that the tests pass as this change only impacts logging.
> Async request mark write complete on success only

- clc/modules/core/src/main/java/com/eucalyptus/component/ServiceUris.java
Public service urls now use the preferred name for the service (e.g. `ec2` not `compute`) and the configured web services port.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=456
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/23/
Test: /job/eucalyptus-5-qa-fast/60/
Demo is that the preferred name is now used in public urls:
```
eucalyptus-5.0.0-0.93.puburls.el7.x86_64
REGION	cloud-1	http://ec2.nc04-euca.appscale.net:8773/
```
> Public service urls should use preferred service name and public port

- clc/modules/core/src/main/java/com/eucalyptus/crypto/util/AbstractKeyStore.java
Improve error handling for an invalid keystore alias.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=458
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/25/
Test: /job/eucalyptus-5-qa-fast/62/
Demo is that there is now a useful error logged when an invalid alias is configured:
```
eucalyptus-5.0.0-0.95.keyalias.el7.x86_64
bootstrap.webservices.ssl.server_alias = invalid-alias
```
Error log will show `/var/log/eucalyptus/cloud-error.log`:
```
Thu Sep 17 21:19:24 2020 ERROR [SslSetup:web-services-worker-pool-35] [com.eucalyptus.crypto.util.SslSetup$1.get(SslSetup.java):423] java.security.KeyStoreException: Key pair not found: inva
lid-alias
java.security.KeyStoreException: Key pair not found: invalid-alias
at …
```
> Key store error handling for unknown alias

- clc/modules/core/src/main/java/com/eucalyptus/util/dns/DnsResolvers.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageBucketResolver.java
We now handle CAA queries without error and allow route53 handling of s3 TXT queries. Passing through the s3 TXT query allows for letsencrypt dns challenges.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=459
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/26/
Test: /job/eucalyptus-5-qa-fast/63/
Demo is that CAA queries no longer fail with an error:
```
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-16.P2.el7_8.6 <<>> s3.nc04-euca.appscale.net caa @192.168.111.14
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39251
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;s3.nc04-euca.appscale.net.	IN	CAA
;; Query time: 1 msec
;; …
```
> DNS handling for CAA and s3 TXT records

- clc/modules/core/src/main/java/com/eucalyptus/util/Cidr.java
- clc/modules/core/src/main/java/com/eucalyptus/util/CompatPredicate.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancingSystemVpcs.java
The load balancing service now checks for conflicts with any existing subnets in the vpc when creating system subnets.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=478
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/33/
Test: /job/eucalyptus-5-qa-fast/67/
Demo is that elb system public/private subnets are now created using the "first" available subnet cidr blocks:
```
eucalyptus-5.0.0-0.102.elbsyssub.el7.x86
SUBNET	subnet-e3064a9355349379a	available	vpc-24d75a8e0ebeaa336	10.254.16.0/20	4091	cloud-1a	false	false
SUBNET	subnet-f49aaa8a381f197a4	available	vpc-fea88d994e5b41f99	172.16.0.0/24	250	cloud-1a	false	false
SUBNET	subnet-990b0443958cab61d	available	vpc-24d75a8e0ebeaa336	10.254.0.0/24	250	cloud-1a	false	false
SUBNET	subnet-06499133a84df1be0	available …
```
> ELB check for conflicts when creating system subnets

- clc/modules/compute-backend/src/main/java/com/eucalyptus/address/AddressManager.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/address/Addresses.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/AllocateAddressType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-2016-11-15-binding.xml
- clc/modules/compute-common-msgs/src/main/resources/ec2-ips-16-11-15.xml
Add `address` parameter to `AllocateAddress` and filter available addresses accordingly on allocation.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=482
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/37/
Test: /job/eucalyptus-5-qa-fast/70/
The demo is that addresses can now be requested on allocation:
```
#
eucalyptus-5.0.0-0.105.ec2ar2.el7.x86_64
#
#
eipalloc-7e4b18f383c4b14bb	vpc	192.168.134.184
#
#
#
#
eipalloc-d2d51045b40e22cb8	vpc	192.168.134.184
#
#
An error occurred (InvalidAddressID.NotFound) when calling the AllocateAddress operation: The requested IP address does not exist or is unavailable
#
```
Fixes corymbia/eucalyptus#211
> EC2 : Support for Elastic IP address recovery

- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/Route53Service.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/Route53Workflow.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/dns/Route53DnsResolver.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/persist/ChangeInfos.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/persist/entities/ChangeInfo.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/persist/entities/PersistenceChangeInfos.java
- clc/modules/route53/src/main/java/com/eucalyptus/route53/service/persist/views/ChangeInfoView.java
Basic implementation for persistent change batch requests using a timer for the pending to insync transition. This allows a short delay while dns records propagate.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=469
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/28/
Test: /job/eucalyptus-5-qa-fast/65/
The demo is that the route53 test suite passes and that changes are present/expired as expected:
```
psql (9.2.24)
Type "help" for help.
eucalyptus_shared=# select creation_timestamp,last_update_timestamp,metadata_unique_name,metadata_state,r53_change_comment from eucalyptus_route53.r53_change;
creation_timestamp    |  last_update_timestamp  |    metadata_unique_name     | metadata_state |             r53_change_comment …
```
> Route53 support for persistent change batch requests

- clc/modules/compute-backend/src/main/java/com/eucalyptus/cloud/run/Allocations.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/images/UnavailableImageInfo.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vm/VmInstanceMetadata.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vm/VmInstances.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/ImageMetadata.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/identifier/ExiResourceIdentifierCanonicalizer.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vm/VmBootRecord.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vm/VmInstances.java
- clc/modules/core/src/main/java/com/eucalyptus/configurable/StaticDatabasePropertyEntry.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/LoadBalancingWorkerProperties.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivities.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingWorkflows.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/ModifyServicePropertiesWorkflow.java
- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/ModifyServicePropertiesWorkflowImpl.java
EC2 image identifiers are now ami/aki/ari by default rather than emi/eki/eri on upgrade a new identifier canonicalizer is enabled to translate to the old naming scheme.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=589
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/80/
Test: /job/eucalyptus-5-qa-fast/95/ (short) /job/eucalyptus-5-qa-suite/186/ (long)
Demo is that `ami` names are used:
```
IMAGE	ami-6a50ba8ce48a52d05	centos-7-x86-64-genericcloud/centos-7-x86_64-genericcloud.manifest.xml	000262227258	available	public	x86_64	machine				instance-store	hvm
```
> EC2 image identifers use ami/aki/ari by default

- clc/modules/core/src/main/java/com/eucalyptus/ws/StackConfiguration.java
The eustore url cloud property configuration was not used.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=587
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/79/
Test: /job/eucalyptus-5-qa-fast/94/
Demo is that the property is no longer present:
```
```
> Remove cloud property configuration for eustore url

- Makefile
- clc/Makefile
- clc/build.xml
- rpm/eucalyptus.spec
Remove empty `/var/lib/eucalyptus/webapps` directory and packaging for `/var/lib/eucalyptus/services`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=529
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/56/
Test: /job/eucalyptus-5-qa-fast/83/
Demo is that directories are not present:
```
eucalyptus-5.0.0-0.121.rpmdirs2.el7.x86_64
backups
bukkits
db
keys
queue
templates
upgrade
volumes
```
> RPM packaging remove unused directories

- clc/modules/core/conf/scripts/setup_membership.groovy
Membership setup options to simplify configuration for the diagnostics handler. There is a new system property `euca.mcast.diagnostics.enable` that can be used to disable the diagnostics port via `eucalyptus.conf` / `CLOUD_OPTS`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=524
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/53/
Test: /job/eucalyptus-5-qa-suite/182/
Demo is that the listen port is not in use when the diagnostics handler is disabled:
```
CLOUD_OPTS="-Denable.route53.tech.preview=true -Denable.sqs.tech.preview=true -Xmx2g  --bind-addr=10.117.111.18 -Deuca.mcast.diagnostics.enable=false"
```
> Membership configuration for diagnostics (JGroups)

- clc/modules/core/src/main/java/com/eucalyptus/configurable/StaticDatabasePropertyEntry.java
Upgrade should set backwards compatible (`euca-`) values for ec2 instance dns name prefix properties.
These properties are new so must be set for compatibility with the existing `cloud.vmstate.instance_subdomain` property.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=614
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/90/
Test: /job/eucalyptus-5-qa-fast/103/
This relates to corymbia/eucalyptus#222
> Upgrade set backwards compatible instance dns cloud properties

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSEC2InstanceTypeResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSEC2InstanceTypeProperties.java
- clc/modules/cluster-common/src/main/java/com/eucalyptus/cluster/common/ResourceState.java
- clc/modules/cluster-common/src/main/java/com/eucalyptus/cluster/common/msgs/VmTypeInfo.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/cloud/run/ClusterAllocator.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/cloud/run/VerifyMetadata.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/images/Emis.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vmtypes/VmTypes.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/vmtypes/VmTypesManager.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/ModifyInstanceTypeAttributeType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VmTypeDetails.java
- clc/modules/compute-common-msgs/src/main/resources/euca-instance-types.xml
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vmtypes/VmType.java
- clc/modules/core/src/main/java/com/eucalyptus/configurable/StaticDatabasePropertyEntry.java
- storage/blobstore.c
- storage/vbr.c
- tools/cf-templates/ec2-instance-types-accelerated.yaml
- tools/cf-templates/ec2-instance-types-compute.yaml
- tools/cf-templates/ec2-instance-types-eucalyptus-4.yaml
- tools/cf-templates/ec2-instance-types-general.yaml
- tools/cf-templates/ec2-instance-types-memory.yaml
- tools/cf-templates/ec2-instance-types-storage.yaml
EC2 instance types are updated to include a disk count which will be zero for "ebs only" instance types. The root device for an `instance-store` instance will now always be the size of one of the ephemeral disks, not the size of the source image.
Using the instance type to define the device size allows instances to expand their file systems on first boot and means you do not have to start with large (when raw) images to get a reasonable root size.
We now create more than one ephemeral disk (instance type allowing) and the number of disks is now checked against the instance type so you can no longer create unlimited ephemeral storage for `ebs` instances.
An option (`cloud.vmtypes.merge_ephemeral_storage`) is added to merge non-root ephemeral disks so that behaviour is similar to previous …
> EC2 instance type and instance-store disk handling

- clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/VolumeUpdateEventListener.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/Volumes.java
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/blockstorage/Volume.java
- clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java
EC2 deleted volume metadata is now deleted as per a configurable expiry.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=659
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/114/
Test: /job/eucalyptus-5-qa-fast/121/
Demo is that the new property can be used:
```
cloud.volumes.deleted_time = 60
```
and that deleted volume metadata expires accordingly.
Fixes Corymbia/eucalyptus#227
> EC2 volume deleted status metadata expiry

- clc/modules/core/src/main/resources/log4j.xml
Log level configuration for apache http core library, which is an aws sdk for java dependency. The `org.apache.http.wire` logger was previously enabled causing wire trace output to be generated for s3 provider (backend) requests. The output was not logged but was impacting s3 performance.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=697
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/130/
Test: /job/eucalyptus-5-qa-fast/124/
Demo is that upload to s3 performance is back to 4.4 levels.
> S3 log level configuration for apache http library

- tools/eucalyptus-cloud.vmoptions
Update vm options to include `-Djdk.tls.ephemeralDHKeySize=matched` for more secure ephemeral Diffie-Hellman key size.
Fixes corymbia/eucalyptus#249
> Web services HTTPS dhe key size match

- tools/clcadmin-assume-system-credentials
The `clcadmin-assume-system-credentials` command can use the wrong key when there are multiple keys with the aliases prefix `eucalyptus`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=860
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/204/
Test: /job/eucalyptus-5-qa-fast/155/
The demo is that the `clcadmin-assume-system-credentials` script works as expected.
> clcadmin-assume-system-credentials can select incorrect key

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/exceptions/s3/NotImplementedException.java
The objectstorage error code is now configurable which can be used to return codes that may be better handled by clients than the default `501`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=847
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/201/
Test: /job/eucalyptus-5-qa-fast/153/
> ObjectStorage configurable error code for unknown actions

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketAccelerateConfigurationResponseType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketAccelerateConfigurationType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketNotificationConfigurationResponseType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketNotificationConfigurationType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketRequestPaymentResponseType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/GetBucketRequestPaymentType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/policy/S3PolicySpec.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/util/ObjectStorageProperties.java
- clc/modules/object-storage-common/src/main/resources/osg-s3ns-binding-inc.xml
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageService.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/binding/ObjectStorageGETBinding.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/binding/ObjectStorageRESTBinding.java
- clc/modules/storage-common/src/main/java/com/eucalyptus/storage/msgs/s3/AccelerateConfiguration.java
- clc/modules/storage-common/src/main/java/com/eucalyptus/storage/msgs/s3/NotificationConfiguration.java
- clc/modules/storage-common/src/main/java/com/eucalyptus/storage/msgs/s3/RequestPaymentConfiguration.java
- clc/modules/storage-common/src/main/resources/s3-2006-03-01-common-binding.xml
Stub implementations are added for the S3 actions:
* GetBucketAccelerateConfiguration
* GetBucketNotificationConfiguration
* GetBucketRequestPayment
to return the default/unconfigured values.
The error codes and http status codes are updated for the S3 actions:
* GetBucketEncryption
* GetBucketReplication
* GetBucketWebsite
* GetObjectLockConfiguration
to match the default not found responses from AWS/S3.
Fixes corymbia/eucalyptus#253
> ObjectStorage stubs/errors for unimplemented actions

- clc/build.gradle
Use azure artifacts hosted glisten rather than bintray/jcenter.
> Repositories Hosted on Bintray
Your repositories for module types including Docker, Maven (Java), Npm, NuGet, RPM, Vagrant, and Generic will need to be migrated off of Bintray service on or before May 1st to avoid any disruption in service.
The gradle build is not used for releases, it is only for developer use so this change is not covered by any tests.
> Use azure artifacts and maven central

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMInstanceProfileResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSIAMInstanceProfileResourceInfo.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSIAMInstanceProfileProperties.java
CloudFormation support for instance profile resource name when using `CAPABILITY_NAMED_IAM`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=897
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/217/
Test: /job/eucalyptus-5-qa-fast/165/
Demo is that named instance profiles can now be created:
```
Type: AWS::IAM::InstanceProfile
Properties:
InstanceProfileName: registry-admin
Roles:
- !Ref AdminRole
--
Type: AWS::IAM::InstanceProfile
Properties:
InstanceProfileName: registry-read
Roles:
- !Ref ReadOnlyRole
arn:aws:cloudformation::000916168637:stack/rds-registry-resources-1/b095620f-e4aa-41cb-8444-c7fedbe301b8
STACK	rds-registry-resources-1	CREATE_COMPLETE		RDS container registry bucket and related IAM resources	2021-02-23T19:43:42.674Z
OUTPUT	Bucket …
```
> CloudFormation support for instance profile resource name

- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/UploadPartCopyResponseType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/msgs/UploadPartCopyType.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/providers/ObjectStorageProviderClient.java
- clc/modules/object-storage-common/src/main/java/com/eucalyptus/objectstorage/util/ObjectStorageProperties.java
- clc/modules/object-storage-common/src/main/resources/osg-s3ns-binding-inc.xml
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectFactory.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectFactoryImpl.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageService.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/binding/ObjectStoragePUTBinding.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/binding/ObjectStorageRESTBinding.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/pipeline/handlers/ObjectStorageOutboundHandler.java
- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/providers/s3/S3ProviderClient.java
- clc/modules/object-storage/src/test/java/com/eucalyptus/objectstorage/providers/InMemoryProvider.java
Object storage gateway support for `UploadPartCopy` action. This allows use of multipart copy with the ceph provider.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=907
Deploy: /job/eucalyptus-internal-5-ado-ansible-deploy/223/
Test: /job/eucalyptus-5-qa-fast/166/
Demo is that when using ceph clients using multipart copy now work.
Fixes corymbia/eucalyptus#260
> S3 UploadPartCopy action

- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/msgs/ModifyStorageVolumeResponseType.java
- clc/modules/block-storage-common/src/main/java/com/eucalyptus/blockstorage/msgs/ModifyStorageVolumeType.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/BlockStorageController.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/BlockStorageService.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/DASManager.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/LogicalStorageManager.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdAdapter.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdFormatTwoAdapter.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/ceph/CephRbdProvider.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/san/common/SANManager.java
- clc/modules/block-storage/src/main/java/com/eucalyptus/blockstorage/san/common/SANProvider.java
- clc/modules/block-storage/src/test/java/com/eucalyptus/blockstorage/BlockStorageUnitTestSupport.java
- clc/modules/block-storage/src/test/java/com/eucalyptus/blockstorage/NoOpStorageManager.java
- clc/modules/block-storage/src/test/java/com/eucalyptus/blockstorage/ProbabalisticFailureStorageManager.java
- clc/modules/compute-backend/src/main/java/com/eucalyptus/blockstorage/VolumeManager.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/ModifyVolumeType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/ModifyVolumeResponseType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/backend/ModifyVolumeType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-ebs-volumes-16-11-15.xml
- clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java
Initial support for EC2 modify volume action for increasing the size of a volume when using ceph storage.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1034
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1037
Demo of resize using ceph with cloud-in-a-box deployment:
```
#
rbd image 'vol-f2a801e6f802d70f3':
size 5 GiB in 1280 objects
order 22 (4 MiB objects)
snapshot_count: 0
id: 111b61bc63be
block_name_prefix: rbd_data.111b61bc63be
format: 2
features: layering
op_features: 
flags: 
create_timestamp: Thu Apr  8 22:55:14 2021
access_timestamp: Thu Apr  8 22:55:14 2021
modify_timestamp: Thu Apr  8 22:55:14 2021
#
#
VOLUMEMODIFICATION	2021-04-08T22:59:23.865Z	completed	5	standard	2021-04-08T22:59:23.785Z	6	standard	vol-f2a801e6f802d70f3
#
# …
```
> EC2 ModifyVolume modify size

- clc/modules/core/src/main/java/com/eucalyptus/bootstrap/BillOfMaterials.java
- clc/modules/core/src/main/java/com/eucalyptus/bootstrap/SystemIds.java
The major version number is now used where necessary for compatibility between different minor versions in a deployment.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1014
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1016
Demo is that only the major version is used (from `cloud-debug.log`):
```
Thu Apr 1 22:46:36 2021  INFO [Hosts:main] Started membership channel Eucalyptus.6.membership.e2cf61dfe1c66d45d87c386b11dd4beacc504d942257c2c669e60eff3b4f74e0
```
Note `Eucalyptus.6.membership` not `Eucalyptus.6.0.0.membership`.
> Use major rather than full version for compatibility

- clc/modules/core/src/main/java/com/eucalyptus/util/dns/DomainNameRecords.java
- clc/modules/dns/src/main/java/com/eucalyptus/dns/resolvers/GenericDnsResolver.java
Configuration for dns ttl / negative ttl is now exposed. The SOA serial is now always static and we use the values from the non-static record `1200 180 2419200 5` (refresh retry expire ttl)
```
...
dns.negative_ttl = 5
...
dns.ttl = 60
...
```
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1076
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1077
Fixes: corymbia/eucalyptus#273
> DNS negative ttl configuration

- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
Merge to master for:
> The object size was off by one byte for each copied part.
> S3 UploadPartCopy action, source end range inclusive (master)

- clc/modules/object-storage/src/main/java/com/eucalyptus/objectstorage/ObjectStorageGateway.java
Update to corymbia/eucalyptus#261 fixing an error in the part size calculation. The object size was off by one byte for each copied part.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1139
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1140
For issue corymbia/eucalyptus#260
> S3 UploadPartCopy action, source end range inclusive

- clc/modules/loadbalancing/src/main/java/com/eucalyptus/loadbalancing/workflow/LoadBalancingActivitiesImpl.java
Fix regression in classic ELB functionality that prevents use of https listeners with a default ssl negotiation policy.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1227
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1228
> ELB https default policy for load balancer

- clc/modules/core/src/main/java/com/eucalyptus/ws/Handlers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/TargetGroups.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroup.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/ws/Loadbalancingv2QueryPipeline.java
ELBv2 clean up for pipeline versions and implement filtering for existing describe actions.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1257
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1258
Demo, filtering load balancers:
```
LOADBALANCERS	2021-05-18T20:49:18.509Z	balancer-1-000377280103.lb.qa64.eucalyptuscloud.net	ipv4	arn:aws:elasticloadbalancing::000377280103:loadbalancer/app/balancer-1/e9790ae22a5f9f2f	balancer-1	internet-facing	application	vpc-95838924301b6fbbc
AVAILABILITYZONES	subnet-78e8d6246176f2db9
SECURITYGROUPS	sg-6b42af7ed1739a6c4
STATE	active
```
filtering target groups:
```
aws elbv2 describe-target-groups --names target-group-1
TARGETGROUPS	30	80	HTTP	arn:aws:elasticloadbalancing::000377280103:targetgroup/target-group-1 …
```
> ELBv2 service filtering for describe actions

- clc/modules/autoscaling-backend/ivy.xml
- clc/modules/autoscaling-backend/src/main/java/com/eucalyptus/autoscaling/activities/ActivityManager.java
- clc/modules/autoscaling-backend/src/main/java/com/eucalyptus/autoscaling/activities/Elbv2Client.java
- clc/modules/autoscaling-backend/src/main/java/com/eucalyptus/autoscaling/backend/AutoScalingBackendService.java
- clc/modules/autoscaling-backend/src/test/java/com/eucalyptus/autoscaling/AutoScalingServiceTest.groovy
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/AutoScalingMessageValidation.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/internal/groups/AutoScalingGroup.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/internal/groups/AutoScalingGroupCoreView.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/internal/groups/AutoScalingGroups.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/msgs/AutoScalingGroupType.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/msgs/CreateAutoScalingGroupType.java
- clc/modules/autoscaling-common/src/main/java/com/eucalyptus/autoscaling/common/msgs/TargetGroupArns.java
- clc/modules/autoscaling-common/src/main/resources/autoscaling-binding.xml
AutoScaling update to support registration of instances against elbv2 target groups.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1254
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1255
Demo is that you can specify target groups for an autoscaling group on creation:
```
--vpc-zone-identifier subnet-78e8d6246176f2db9 \
--availability-zones cloud-1a \
--min-size 0 \
--max-size 1 \
--desired-capacity 1 \
--target-group-arns arn:aws:elasticloadbalancing::000377280103:targetgroup/target-group-1/e2ead7352dd826d2 \
--launch-configuration-name config-1 \
--auto-scaling-group-name group-1
```
and instances created for the group are then registered with the target group (load balancer):
```
TARGET	i-78941a5791f410c3d
TARGETHEALTH …
```
> AutoScaling ELBv2 target group support

- clc/modules/euare-common/src/main/java/com/eucalyptus/auth/euare/common/EuareApi.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Workflow.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Listener.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/ListenerView.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerListenersView.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerView.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/servo/Loadbalancingv2ServoMetadataSource.java
- clc/modules/loadbalancingv2/src/main/resources/com/eucalyptus/loadbalancingv2/service/loadbalancer-app-zone.yaml
- clc/modules/loadbalancingv2/src/main/resources/com/eucalyptus/loadbalancingv2/service/loadbalancer-net-zone.yaml
ELBv2 support for creation of listeners with a server certificate for https/tls.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1263
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1264
Demo:
```
--load-balancer-arn arn:aws:elasticloadbalancing::000186855777:loadbalancer/app/balancer-1/932cbc625b79bb3e \
--port 443 \
--protocol HTTPS \
--certificates CertificateArn=arn:aws:iam::000186855777:server-certificate/1ab13b3f-f5f9-0/1ab13b3f-f5f9-elb \
--default-actions Type=forward,TargetGroupArn=arn:aws:elasticloadbalancing::000186855777:targetgroup/target-group-1/b2589b768b605043
```
> ELBv2 https/tls listener server certificate

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMGroupResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMInstanceProfileResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMManagedPolicyResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMPolicyResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMRoleResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMUserResourceAction.java
CloudFormation IAM names now limited to the maximum length permitted for each resource type.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1279
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1280
The test failure with s3 is due to a fix not being present at the branch point and not related to this issue.
Fixes corymbia/eucalyptus#292
> CloudFormation IAM maximum identifier lengths

- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMGroupResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMInstanceProfileResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMManagedPolicyResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMPolicyResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMRoleResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSIAMUserResourceAction.java
Merge to master for 5.2 fix.
> CloudFormation IAM names now limited to the maximum length permitted for each resource type.
Relates to corymbia/eucalyptus#293
> CloudFormation IAM maximum identifier lengths (master)

- clc/modules/cloudformation/ivy.xml
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/ResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSAutoScalingAutoScalingGroupResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2ListenerResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2LoadBalancerResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/actions/AWSElasticLoadBalancingV2TargetGroupResourceAction.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSElasticLoadBalancingV2ListenerResourceInfo.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSElasticLoadBalancingV2LoadBalancerResourceInfo.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/info/AWSElasticLoadBalancingV2TargetGroupResourceInfo.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSAutoScalingAutoScalingGroupProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSElasticLoadBalancingV2ListenerProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSElasticLoadBalancingV2LoadBalancerProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/AWSElasticLoadBalancingV2TargetGroupProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2ActionProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2CertificateProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2FixedResponseConfigProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2ForwardConfigProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2LoadBalancerAttributeProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2MatcherProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2RedirectConfigProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2SubnetMappingProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2TargetDescriptionProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2TargetGroupAttributeProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2TargetGroupStickinessConfigProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/resources/standard/propertytypes/ElasticLoadBalancingV2TargetGroupTupleProperties.java
- clc/modules/cloudformation/src/main/java/com/eucalyptus/cloudformation/util/MessageHelper.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
Initial cloudformation support for elbv2 resources:
* `AWS::ElasticLoadBalancingV2::Listener`
* `AWS::ElasticLoadBalancingV2::LoadBalancer`
* `AWS::ElasticLoadBalancingV2::TargetGroup`
and the `TargetGroupARNs` property of `AWS::AutoScaling::AutoScalingGroup` for autoscaling backed load balancers.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1282
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1283
Manual testing covered templates with:
* http load balancer with cloudformation registered target instance
* https loadbalancer with cloudformation registered target instance
* http loadbalancer with autoscaling registered target instance
> CloudFormation support for elbv2

- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerView.java
ELBv2 support for route53 alias target.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1289
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1290
Demo is that you can reference an elbv2 load balancer using a route53 alias target:
```
#
10.111.10.179
#
#
10.111.10.179
#
#
```
where `example.com` is a route53 hosted zone with an alias target record for `elb.example.com`.
> ELBv2 route53 hosted zone for load balancers

- clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/Loadbalancingv2.java
ELBv2 output service account information for describe services to allow elbv2 account discovery.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1344
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1345
Demo is that account information can now be discovered:
```
SERVICE  arn:euca:bootstrap:api.10.111.10.64:loadbalancingv2:api.10.111.10.64.loadbalancingv2/  enabled  25  http://10.111.10.64:8773/services/Loadbalancingv2  (eucalyptus)loadbalancing=000576293336:443d94e5d102e5161152e311518365743315446622b16352e63254f5134242d5
```
> ELBv2 service account metadata

- clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/Limit.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2LimitProperties.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/TargetGroups.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/Listener.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroup.java
ELBv2 configurable service limits.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1323
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1324
Cloud properties for limits are added:
```
services.loadbalancingv2.limit.application_load_balancers = 50
services.loadbalancingv2.limit.certificates_per_application_load_balancer = 25
services.loadbalancingv2.limit.certificates_per_network_load_balancer = 25
services.loadbalancingv2.limit.condition_values_per_alb_rule = 5
services.loadbalancingv2.limit.condition_wildcards_per_alb_rule = 5
services.loadbalancingv2.limit.listeners_per_application_load_balancer = 50
services.loadbalancingv2.limit.listeners_per_network_load_balancer = 50
services.loadbalancingv2.limit.max_tags = 50 …
```
> ELBv2 limits

- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/ComputeApi.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Workflow.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancerSubnet.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerSubnetView.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerView.java
ELBv2 support for load balancers in multiple zones.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1326
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1327
Demo is that the zone is now displayed (`cloud-1a`):
```
LOADBALANCERS	ZAAHYUWFUZQSVF	2021-06-04T23:16:51.688Z	balancer-1-000132709131.lb.qa64.eucalyptuscloud.net	ipv4	arn:aws:elasticloadbalancing::000132709131:loadbalancer/app/balancer-1/56f824cd0e9f40d3	balancer-1	internet-facing	application	vpc-d861259f7b9434256
AVAILABILITYZONES	subnet-bca8d02b764312d45	cloud-1a
SECURITYGROUPS	sg-4d2a20839896708d9
STATE	active
```
and that deployed stacks include the zone name, e.g. `loadbalancer-app-000132709131-cloud-1a-balancer-1`.
> ELBv2 support for multiple zones

- clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/LoadBalancerAttribute.java
- clc/modules/loadbalancingv2-common/src/main/java/com/eucalyptus/loadbalancingv2/common/msgs/TargetGroupAttribute.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancingAttribute.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/TargetGroups.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/LoadBalancer.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/entities/TargetGroup.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/servo/Loadbalancingv2ServoMetadataSource.java
ELBv2 attributes for load balancers and target groups.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1338
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1339
Demo is that attributes can be described and modified:
```
#
ATTRIBUTES	access_logs.s3.enabled	true
ATTRIBUTES	access_logs.s3.bucket	elblogs
ATTRIBUTES	access_logs.s3.prefix	logs
ATTRIBUTES	deletion_protection.enabled	false
ATTRIBUTES	idle_timeout.timeout_seconds	60
ATTRIBUTES	routing.http.desync_mitigation_mode	defensive
ATTRIBUTES	routing.http.drop_invalid_header_fields.enabled	false
ATTRIBUTES	routing.http2.enabled	true
ATTRIBUTES	waf.fail_open.enabled	false
#
#
ATTRIBUTES	deregistration_delay.timeout_seconds	300
ATTRIBUTES	deregistration_delay.connection_termination.enabled	false …
```
> ELBv2 load balancer and target group attributes

- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Service.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/Loadbalancingv2Workflow.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/LoadBalancers.java
- clc/modules/loadbalancingv2/src/main/java/com/eucalyptus/loadbalancingv2/service/persist/views/LoadBalancerListenersView.java
- clc/modules/loadbalancingv2/src/main/resources/com/eucalyptus/loadbalancingv2/service/loadbalancer-app-zone.yaml
- clc/modules/loadbalancingv2/src/main/resources/com/eucalyptus/loadbalancingv2/service/loadbalancer-net-zone.yaml
ELBv2 servo instances are now deployed with an iam instance profile permitting s3 object puts for access logging.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1354 
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1355
Manually tested by verifying that access logs are present in the expected s3 location when logging is enabled and there is traffic to the load balancer.
> ELBv2 s3 access logging permissions

- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/RdsMessageValidation.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/CreateDBInstanceType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/CreateDBSubnetGroupType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DBSecurityGroupNameList.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DeleteDBInstanceType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DeleteDBSubnetGroupType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DescribeDBEngineVersionsType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DescribeDBInstancesType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/DescribeDBSubnetGroupsType.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/Filter.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/FilterValueList.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/LogTypeList.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/ProcessorFeature.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/SubnetIdentifierList.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/Tag.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/msgs/VpcSecurityGroupIdList.java
- clc/modules/rds-common/src/test/java/com/eucalyptus/rds/common/RdsMessageValidationSpecification.groovy
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/RdsService.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/RdsWorkflow.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/dns/RdsDnsResolver.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/DBInstances.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/DBSubnetGroups.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/persist/entities/RdsPersistenceSupport.java
RDS service request validation as per api.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1375
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1376
Verified that existing manual rds tests pass with changes in place:
```
...
...
...
...
DBINSTANCES	1	False	cloud-1a	0	False	arn:aws:rds::000340531378:db/database-1	db.t2.small	database-1	available	postgres	postgres	11	False	2021-06-22T05:18:36.529Z	username	False	False	True	False
DBSUBNETGROUP	arn:aws:rds::000340531378:subgrp/subnet-group-1	A subnet group description	subnet-group-1	Complete	vpc-547b1fdf520a27975
SUBNETS	subnet-72bee31afbbfcc9f6	Active
SUBNETAVAILABILITYZONE	cloud-1a
ENDPOINT	database-1.s5afpqfhme5h.rds.qa64.eucalyptuscloud.net	5432
VPCSECURITYGROUPS	active	sg-44fd450ab677ef6e3
# …
```
> RDS service request validation

- rpm/eucalyptus.spec
Merge to master for corymbia/eucalyptus#312
> Update to the rpm packaging for eucanetd to require nginx-mod-http-perl which used to be a transitive dependency of nginx via nginx-all-modules.
Relates to corymbia/eucalyptus#311
> eucanetd packaging updated to require nginx-mod-http-perl (master)

- rpm/eucalyptus.spec
Update to the rpm packaging for `eucanetd` to require `nginx-mod-http-perl` which used to be a transitive dependency of `nginx` via `nginx-all-modules`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1382
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1385
Fixes corymbia/eucalyptus#311
> eucanetd packaging updated to require nginx-mod-http-perl

- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/policy/RdsErnBuilder.java
- clc/modules/rds-common/src/main/java/com/eucalyptus/rds/common/policy/RdsResourceName.java
- clc/modules/rds/src/main/java/com/eucalyptus/rds/service/RdsService.java
Filtering support for DescribeDBInstances and correct the arn format / parsing.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1392
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1393
Demo is that filters can now be used:
```
DBINSTANCES	1	False	cloud-1a	0	False	arn:aws:rds::000328023357:db:database-1	db.t2.small	database-1	available	postgres	postgres	11	False	2021-06-23T20:52:40.913Z	username	False	False	True	False
DBSUBNETGROUP	arn:aws:rds::000328023357:subgrp:subnet-group-1	A subnet group description	subnet-group-1	Complete	vpc-2d23a9de2fd65a890
SUBNETS	subnet-9d104ca1f40f41874	Active
SUBNETAVAILABILITYZONE	cloud-1a
ENDPOINT	database-1.qzquzxvpj1wx.rds.qa64.eucalyptuscloud.net	5432
VPCSECURITYGROUPS	active	sg-9ed2dfa280ced0144
``` …
> RDS DescribeDBInstances filtering

- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/DescribeVpcClassicLinkResponseType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/DescribeVpcClassicLinkType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcClassicLinkSetType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcClassicLinkType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-14-10-01.xml
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-15-10-01.xml
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vpc/Vpcs.java
- clc/modules/compute-service/src/main/java/com/eucalyptus/compute/service/ComputeService.java
Fix the query request binding for the ec2 vpc `DescribeVpcClassicLink` action and add a hard-coded false response for the classic link status of all vpcs.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1446
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1447
Test was run against this fix merged to maint-5.
Demo is that the action now binds the request and returns a hard-coded response:
```
VPCS	False	vpc-bcf46a40cb2d2e859
```
Relates to corymbia/eucalyptus#321
> EC2 VPC DescribeVpcClassicLink binding and response

- clc/modules/autoscaling-common/src/main/resources/autoscaling-binding.xml
The `AvailabilityZones` structure is now optional in the `CreateAutoScalingGroup` binding.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1451
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1452
Tests were run against this pull request merged to maint-5.
Demo is to create a vpc without specifying zones:
```
```
Relates to corymbia/eucalyptus#324
> AutoScaling group creation should not require availability zones

- clc/modules/autoscaling-common/src/main/resources/autoscaling-binding.xml
Merge to master for the 5.2 pull request corymbia/eucalyptus#325
> The AvailabilityZones structure is now optional in the CreateAutoScalingGroup binding.
Relates to corymbia/eucalyptus#324
> AutoScaling group creation should not require availability zones (master)

- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/ModifySubnetAttributeType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/SubnetType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
EC2 vpc subnet attribute stub implementations for `assignIpv6AddressOnCreation` and `mapCustomerOwnedIpOnLaunch`.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1458
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1459
Demo is that you can modify the attributes:
```
```
Relates to corymbia/eucalyptus#327
> EC2 VPC subnet attribute stubs for customer and ipv6 ip addresses

- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/ModifySubnetAttributeType.java
- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/SubnetType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
Merge to master for 5.2 fix corymbia/eucalyptus#328
> EC2 vpc subnet attribute stub implementations for assignIpv6AddressOnCreation and mapCustomerOwnedIpOnLaunch.
Relates to corymbia/eucalyptus#327
> EC2 VPC subnet attribute stubs for customer and ipv6 ip addresses (master)

- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vpc/Vpcs.java
EC2 VPC cidr association is now stubbed in describe vpc responses and can be used for filtering when describing vpcs.
Build: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1458
Test: https://dev.azure.com/corymbia/eucalyptus/_build/results?buildId=1459
Demo is that you can filter on the cidr association:
```
Name=cidr-block-association.association-id,Values=vpc-cidr-assoc-bcf46a40cb2d2e859 \
Name=cidr-block-association.state,Values=associated \
Name=cidr-block-association.cidr-block,Values=172.31.0.0/16
VPCS	172.31.0.0/16	dopt-2423079a7f8376dff	default	True	available	vpc-bcf46a40cb2d2e859
CIDRBLOCKASSOCIATIONSET	vpc-cidr-assoc-bcf46a40cb2d2e859	172.31.0.0/16
CIDRBLOCKSTATE	associated
```
Relates to corymbia/eucalyptus#330
> EC2 VPC cidr association information for main cidr

- clc/modules/compute-common-msgs/src/main/java/com/eucalyptus/compute/common/VpcType.java
- clc/modules/compute-common-msgs/src/main/resources/ec2-vpc-16-11-15.xml
- clc/modules/compute-common/src/main/java/com/eucalyptus/compute/common/internal/vpc/Vpcs.java
Merge to master for 5.2 pull request corymbia/eucalyptus#331
> EC2 VPC cidr association is now stubbed in describe vpc responses and can be used for filtering when describing vpcs.
Relates to corymbia/eucalyptus#330
> EC2 VPC cidr association information for main cidr (master)
